In [1]:
from pathlib import Path
from shutil import copyfile, rmtree
import pandas as pd

In [2]:
DATA_DIR = Path('.') / 'data'

GOLD_LAB_DIR = DATA_DIR / 'gold_labels'
GOLD_RAW_DIR = DATA_DIR / 'gold_raw_data'

RAW_DIR = DATA_DIR / 'images'
TYPEWRITTEN_DIR = DATA_DIR / 'typewritten'

GOLD_STD = DATA_DIR / 'GoldStandard_type100.csv'
GOLD_STD = DATA_DIR / 'GoldStandardExtraction_NewOCR200.csv'

SUB_ID = 'subject_id'

In [3]:
rmtree(GOLD_LAB_DIR, ignore_errors=True)
rmtree(GOLD_RAW_DIR, ignore_errors=True)

GOLD_LAB_DIR.mkdir()
GOLD_RAW_DIR.mkdir()

In [4]:
df = pd.read_csv(GOLD_STD)
df.head()

,subject_id,category,class,box,path,original,predicted_class,predicted_category,predicted_box,predicted_text,RPG quality score,Unnamed: 11,Date,Scientific_Name + Authority,Collector Name,Collector #
0,11782933.0,typewritten,2.0,"[429, 1216, 757, 1467]",data/valid/11782933.jpg,data/images/11782933.jpg,2.0,typewritten,[ 421.10596 1210.5048 759.9078 1466.8336 ],PLANTS OF ARKANSAS\nPamily.. ASGLEP TA DAC BAG...,1,NaN,fail,fail,fail,fail
1,11782141.0,typewritten,2.0,"[550, 1211, 929, 1438]",data/valid/11782141.jpg,data/images/11782141.jpg,2.0,typewritten,[ 545.36285 1211.1482 932.15137 1441.8547 ],Hendrix College Herbarium\nae ee. 8 - me =\nV ...,1,NaN,fail,fail,fail,fail
2,11782436.0,typewritten,2.0,"[615, 1132, 971, 1459]",data/valid/11782436.jpg,data/images/11782436.jpg,2.0,typewritten,[ 610.84015 1154.6107 974.8648 1461.4298 ],University of Arkansas Herbarium (UARK)\nFlora...,4,NaN,14 June 2005,Dichanthelium commutatum (Schult.) Gould subsp.,R. McElderry and J. Bost,1683
3,4128609.0,typewritten,2.0,"[147, 290, 234, 360]",data/valid/4128609.jpg,data/images/4128609.jpg,2.0,typewritten,[150.56839 294.10455 245.20482 372.7297 ],"PLANTS OF_ TENNESSEE __ _—_——\n\n4, Wieka ——",1,NaN,fail,fail,fail,fail
4,11782773.0,typewritten,2.0,"[534, 1224, 944, 1468]",data/valid/11782773.jpg,data/images/11782773.jpg,2.0,typewritten,[ 532.0969 1217.4865 954.4897 1472.3646],University of Arkansas Herbarium (UARK)\nFlora...,4,NaN,18 October 2002,Solidago canadensis L.,Sarah Nunn with Angela Brown,7391

In [7]:
for subject_id in df.subject_id:
    print(subject_id)
    file_name = str(int(subject_id)) + '.jpg'

    src = RAW_DIR / file_name
    dst = GOLD_RAW_DIR / file_name
    copyfile(src, dst)

    src = TYPEWRITTEN_DIR / file_name
    dst = GOLD_LAB_DIR / file_name
    copyfile(src, dst)

11782933.0
11782141.0
11782436.0
4128609.0
11782773.0
11783209.0
10668273.0
11781299.0
11781178.0
11783420.0
11782801.0
11780091.0
2995238.0
4128893.0
10667756.0
11783670.0
2995389.0
11779977.0
2995489.0
4128217.0
11779986.0
11781249.0
4128253.0
2995308.0
11780694.0
10668173.0
11782879.0
2995203.0
11780125.0
2995363.0
11782634.0
11783320.0
10667953.0
2995450.0
11780143.0
10667562.0
11780760.0
11781333.0
11781143.0
2995589.0
11779805.0
4128573.0
11781045.0
2995456.0
10668176.0
11781309.0
11782745.0
10668282.0
11781446.0
11779851.0
2995458.0
11781429.0
11781597.0
11780060.0
11782825.0
11783310.0
11782222.0
10667659.0
4128724.0
10667656.0
4128377.0
11783387.0
11780775.0
10667444.0
11780767.0
11779960.0
4128353.0
2995202.0
11781325.0
2995581.0
4128182.0
4128668.0
11782306.0
11780030.0
11781685.0
10667549.0
11780847.0
11780388.0
2995419.0
11781476.0
2995442.0
11781035.0
11782152.0
2995548.0
11782173.0
11783195.0
11783369.0
10667978.0
11780963.0
11782345.0
11782108.0
11782620.0
11780631.0
11779943.0
11780448.0
11781873.0
10667908.0
10667637.0
11781233.0
11783172.0
4128909.0
10668149.0
10668197.0
11780467.0
11783287.0
11781673.0
11783684.0
11780995.0
11780208.0
11781269.0
10667753.0
11782164.0
11780080.0
11783403.0
11781554.0
11779862.0
11781638.0
11780582.0
4128735.0
11783427.0
4128501.0
10668049.0
4128797.0
11783299.0
4128856.0
11783519.0
4128416.0
11781659.0
11782129.0
4128419.0
4128354.0
11782577.0
11780854.0
2995378.0
11782394.0
10668066.0
4128150.0
11780946.0
11781761.0
11780255.0
11781485.0
11783689.0
2995593.0
11783147.0
4128910.0
11783557.0
10667554.0
11781042.0
11780399.0
11781713.0
4128594.0
11780773.0
4128330.0
11782275.0
11782794.0
2995459.0
11781572.0
11782989.0
11782490.0
4128713.0
2995434.0
10667606.0
11782762.0
11781842.0
10668179.0
11783070.0
10668272.0
10667960.0
11779925.0
11779837.0
11780705.0
11781820.0
11782752.0
4128376.0
11782292.0
4128309.0
4128684.0
11781595.0
4128404.0
11781085.0
11780787.0
11783650.0
10667911.0
11780730.0
11783131.0
4128339.0
11783163.0
11780568.0
10667833.0
11781148.0
4128192.0
11780961.0
10668052.0
11780960.0
11781830.0
11782433.0
11782885.0
11782451.0
11783737.0
10667446.0
nan

ValueError: cannot convert float NaN to integer